language: rust
cache: cargo
sudo: required
dist: trusty

os:
  - linux
  - osx

# run builds for both all the trains
rust:
  - stable
  - beta
  - nightly

before_script:
  - |
      pip install git+https://github.com/huonw/travis-cargo --user &&
      git clone https://github.com/sstephenson/bats/ &&
      export WORKSPACE=$HOME/workspace &&
      mkdir $WORKSPACE &&
      cp -a $TRAVIS_BUILD_DIR/tests/integration/fixtures/* $WORKSPACE &&
      export PATH=$HOME/.local/bin:$(pwd)/bats/bin:$TRAVIS_BUILD_DIR/target/debug:/Users/travis/Library/Python/2.7/bin:$PATH &&
      git config --global user.name semantic-rs &&
      git config --global user.email semantic@rs
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install libssh2; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then export PKG_CONFIG_PATH=/usr/local/Cellar/openssl/1.0.2l/lib/pkgconfig; fi


script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      pushd tests/integration && bats integration.bats && popd &&
      travis-cargo --only stable doc

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

notifications:
  email: false
