[package]
name = "semantic-rs"
version = "0.1.0"
authors = ["Jan Schulte <hello@unexpected-co.de>", "Jan-Erik Rediger <janerik@fnordig.de>"]
description = "Automatic crate publishing"

[dependencies]
term = "0.2"
toml = "0.1"
regex = "0.1"
semver = "0.2.1"
commit_walker = { git = "https://github.com/semantic-rs/commit-walker" }
commit_analyzer = { git = "https://github.com/semantic-rs/commit-analyzer" }
