[package]
name = "semantic-rs"
version = "0.1.0"
authors = ["Jan Schulte <hello@unexpected-co.de>", "Jan-Erik Rediger <janerik@fnordig.de>"]
description = "Automatic crate publishing"
license = "MIT"

[dependencies]
term = "0.2"
toml = "0.1"
regex = "0.1"
semver = "0.2.1"
commit_walker = { git = "https://github.com/semantic-rs/commit-walker" }
commit_analyzer = { git = "https://github.com/semantic-rs/commit-analyzer" }
argparse = "0.2.1"
git2-commit = { git = "https://github.com/badboy/git2-commit-rs" }
git2 = "0.3.4"
